# Generated by Django 6.0.3 on 2026-08-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_volunteerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='volunteer_images/'),
        ),
    ]
