# Generated by Django 6.0.3 on 2026-08-01 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='email',
        ),
        migrations.AddField(
            model_name='ngo',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('current_volunteers', models.PositiveIntegerField(default=0)),
                ('required_volunteers', models.PositiveIntegerField()),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='ngo.ngo')),
            ],
        ),
    ]
