# Generated by Django 6.0.3 on 2026-08-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_remove_ngo_email_ngo_city_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='ngo_campaigns/'),
        ),
    ]
