# Generated by Django 6.0.3 on 2026-07-29 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('prompt_template', models.TextField()),
                ('icon', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrowthRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lifespan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LightRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('temperature_min', models.IntegerField()),
                ('temperature_max', models.IntegerField()),
                ('humidity', models.CharField(max_length=50)),
                ('average_height', models.CharField(max_length=50)),
                ('fertilizer', models.CharField(max_length=100)),
                ('repotting_frequency', models.CharField(max_length=50)),
                ('pruning_required', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('air_purifying', models.BooleanField(default=False)),
                ('edible', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plants.category')),
                ('growth_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plants.growthrate')),
                ('home_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_place_plants', to='plants.homeplace')),
                ('lifespan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plants.lifespan')),
                ('light_requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plants.lightrequirement')),
                ('plant_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plants.planttype')),
                ('best_planting_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planting_plants', to='plants.season')),
                ('flowering_season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flowering_plants', to='plants.season')),
                ('fruiting_season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fruiting_plants', to='plants.season')),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plants.soiltype')),
                ('water_requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plants.waterrequirement')),
            ],
        ),
        migrations.CreateModel(
            name='PlantFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.faqquestion')),
            ],
            options={
                'unique_together': {('plant', 'question')},
            },
        ),
    ]
