# Generated by Django 6.0.3 on 2026-07-27 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_homeplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='home_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plants.homeplace'),
        ),
    ]
